# Generated by Django 4.0.1 on 2022-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('img', models.FileField(upload_to='', verbose_name='Изображение')),
                ('views', models.IntegerField(verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новость',
            },
        ),
    ]
