# Generated by Django 4.0.1 on 2022-01-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='img',
            field=models.FileField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
