# Generated by Django 4.0.1 on 2022-01-24 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testworkapp', '0002_alter_newslist_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslist',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 13, 27, 27, 87740), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(default='Anonymus', max_length=20, verbose_name='Пользователь')),
                ('Text', models.TextField(verbose_name='Текст коментария')),
                ('nameArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testworkapp.newslist')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
