# Generated by Django 4.0.1 on 2022-01-24 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testworkapp', '0003_alter_newslist_options_alter_newslist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 13, 36, 3, 936490), verbose_name='Дата создания'),
        ),
    ]
