# Generated by Django 4.0.1 on 2022-01-25 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testworkapp', '0008_alter_comment_date_alter_newslist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backsaids',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 51, 11, 984733), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 51, 11, 983729), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 51, 11, 981730), verbose_name='Дата создания'),
        ),
    ]
