# Generated by Django 4.0.1 on 2022-01-25 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testworkapp', '0009_backsaids_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backsaids',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 59, 18, 421110), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 59, 18, 419112), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 11, 59, 18, 418112), verbose_name='Дата создания'),
        ),
    ]
